name: Monthly FOI Worker

on:
  schedule:
    - cron: '0 10 * * *' # Runs daily at 10:00 UTC
  workflow_dispatch:      # Manual trigger button
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Update Script
        run: bash update.sh

      - name: Commit and Push
        run: |
          git config user.name "ISTAT"
          git config user.email "istat@istat.it"
          git add *.json
          git commit -m "Update data: $(date +'%Y-%m')" || exit 0
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4